server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: uri
      database: spring-boot-dev

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: uri
      database: spring-boot-prod