server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-request-size: 6MB
      max-file-size: 6MB

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: uri
      database: spring-boot-dev

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: uri
      database: spring-boot-prod